/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZkEvmVerifier,
  IZkEvmVerifierInterface,
} from "../../../../src/libraries/verifier/IZkEvmVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "aggrProof",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "publicInputHash",
        type: "bytes32",
      },
    ],
    name: "verify",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZkEvmVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZkEvmVerifierInterface {
    return new Interface(_abi) as IZkEvmVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZkEvmVerifier {
    return new Contract(address, _abi, runner) as unknown as IZkEvmVerifier;
  }
}
