/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface L1BlockContainerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBlockTimestamp"
      | "getStateRoot"
      | "importBlockHeader"
      | "initialize"
      | "latestBaseFee"
      | "latestBlockHash"
      | "latestBlockNumber"
      | "latestBlockTimestamp"
      | "metadata"
      | "owner"
      | "renounceOwnership"
      | "stateRoot"
      | "transferOwnership"
      | "updateWhitelist"
      | "whitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ImportBlock"
      | "OwnershipTransferred"
      | "UpdateWhitelist"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getBlockTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importBlockHeader",
    values: [BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestBaseFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestBlockHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestBlockTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "metadata", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "whitelist", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getBlockTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importBlockHeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestBaseFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestBlockTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stateRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
}

export namespace ImportBlockEvent {
  export type InputTuple = [
    blockHash: BytesLike,
    blockHeight: BigNumberish,
    blockTimestamp: BigNumberish,
    baseFee: BigNumberish,
    stateRoot: BytesLike
  ];
  export type OutputTuple = [
    blockHash: string,
    blockHeight: bigint,
    blockTimestamp: bigint,
    baseFee: bigint,
    stateRoot: string
  ];
  export interface OutputObject {
    blockHash: string;
    blockHeight: bigint;
    blockTimestamp: bigint;
    baseFee: bigint;
    stateRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [_oldOwner: AddressLike, _newOwner: AddressLike];
  export type OutputTuple = [_oldOwner: string, _newOwner: string];
  export interface OutputObject {
    _oldOwner: string;
    _newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateWhitelistEvent {
  export type InputTuple = [
    _oldWhitelist: AddressLike,
    _newWhitelist: AddressLike
  ];
  export type OutputTuple = [_oldWhitelist: string, _newWhitelist: string];
  export interface OutputObject {
    _oldWhitelist: string;
    _newWhitelist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface L1BlockContainer extends BaseContract {
  connect(runner?: ContractRunner | null): L1BlockContainer;
  waitForDeployment(): Promise<this>;

  interface: L1BlockContainerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBlockTimestamp: TypedContractMethod<
    [_blockHash: BytesLike],
    [bigint],
    "view"
  >;

  getStateRoot: TypedContractMethod<[_blockHash: BytesLike], [string], "view">;

  importBlockHeader: TypedContractMethod<
    [
      _blockHash: BytesLike,
      _blockHeaderRLP: BytesLike,
      _updateGasPriceOracle: boolean
    ],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _startBlockHash: BytesLike,
      _startBlockHeight: BigNumberish,
      _startBlockTimestamp: BigNumberish,
      _startBlockBaseFee: BigNumberish,
      _startStateRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  latestBaseFee: TypedContractMethod<[], [bigint], "view">;

  latestBlockHash: TypedContractMethod<[], [string], "view">;

  latestBlockNumber: TypedContractMethod<[], [bigint], "view">;

  latestBlockTimestamp: TypedContractMethod<[], [bigint], "view">;

  metadata: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        height: bigint;
        timestamp: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stateRoot: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWhitelist: TypedContractMethod<
    [_newWhitelist: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelist: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBlockTimestamp"
  ): TypedContractMethod<[_blockHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStateRoot"
  ): TypedContractMethod<[_blockHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "importBlockHeader"
  ): TypedContractMethod<
    [
      _blockHash: BytesLike,
      _blockHeaderRLP: BytesLike,
      _updateGasPriceOracle: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _startBlockHash: BytesLike,
      _startBlockHeight: BigNumberish,
      _startBlockTimestamp: BigNumberish,
      _startBlockBaseFee: BigNumberish,
      _startStateRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "latestBaseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "latestBlockHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "latestBlockNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "latestBlockTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "metadata"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        height: bigint;
        timestamp: bigint;
        baseFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stateRoot"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelist"
  ): TypedContractMethod<[_newWhitelist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ImportBlock"
  ): TypedContractEvent<
    ImportBlockEvent.InputTuple,
    ImportBlockEvent.OutputTuple,
    ImportBlockEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateWhitelist"
  ): TypedContractEvent<
    UpdateWhitelistEvent.InputTuple,
    UpdateWhitelistEvent.OutputTuple,
    UpdateWhitelistEvent.OutputObject
  >;

  filters: {
    "ImportBlock(bytes32,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      ImportBlockEvent.InputTuple,
      ImportBlockEvent.OutputTuple,
      ImportBlockEvent.OutputObject
    >;
    ImportBlock: TypedContractEvent<
      ImportBlockEvent.InputTuple,
      ImportBlockEvent.OutputTuple,
      ImportBlockEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateWhitelist(address,address)": TypedContractEvent<
      UpdateWhitelistEvent.InputTuple,
      UpdateWhitelistEvent.OutputTuple,
      UpdateWhitelistEvent.OutputObject
    >;
    UpdateWhitelist: TypedContractEvent<
      UpdateWhitelistEvent.InputTuple,
      UpdateWhitelistEvent.OutputTuple,
      UpdateWhitelistEvent.OutputObject
    >;
  };
}
