/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as draftL2UsdcGatewayCctpSol from "./draft-L2USDCGatewayCCTP.sol";
export { L2USDCGateway__factory } from "./L2USDCGateway__factory";
