/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface L1ERC1155GatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchDepositERC1155(address,uint256[],uint256[],uint256)"
      | "batchDepositERC1155(address,address,uint256[],uint256[],uint256)"
      | "counterpart"
      | "depositERC1155(address,address,uint256,uint256,uint256)"
      | "depositERC1155(address,uint256,uint256,uint256)"
      | "finalizeBatchWithdrawERC1155"
      | "finalizeWithdrawERC1155"
      | "initialize"
      | "messenger"
      | "onDropMessage"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "owner"
      | "renounceOwnership"
      | "router"
      | "supportsInterface"
      | "tokenMapping"
      | "transferOwnership"
      | "updateTokenMapping"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchDepositERC1155"
      | "BatchRefundERC1155"
      | "DepositERC1155"
      | "FinalizeBatchWithdrawERC1155"
      | "FinalizeWithdrawERC1155"
      | "Initialized"
      | "OwnershipTransferred"
      | "RefundERC1155"
      | "UpdateTokenMapping"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchDepositERC1155(address,uint256[],uint256[],uint256)",
    values: [AddressLike, BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchDepositERC1155(address,address,uint256[],uint256[],uint256)",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "counterpart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC1155(address,address,uint256,uint256,uint256)",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC1155(address,uint256,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBatchWithdrawERC1155",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawERC1155",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "messenger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onDropMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMapping",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenMapping",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchDepositERC1155(address,uint256[],uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchDepositERC1155(address,address,uint256[],uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterpart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC1155(address,address,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC1155(address,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBatchWithdrawERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messenger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onDropMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenMapping",
    data: BytesLike
  ): Result;
}

export namespace BatchDepositERC1155Event {
  export type InputTuple = [
    _l1Token: AddressLike,
    _l2Token: AddressLike,
    _from: AddressLike,
    _to: AddressLike,
    _tokenIds: BigNumberish[],
    _amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    _l1Token: string,
    _l2Token: string,
    _from: string,
    _to: string,
    _tokenIds: bigint[],
    _amounts: bigint[]
  ];
  export interface OutputObject {
    _l1Token: string;
    _l2Token: string;
    _from: string;
    _to: string;
    _tokenIds: bigint[];
    _amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRefundERC1155Event {
  export type InputTuple = [
    token: AddressLike,
    recipient: AddressLike,
    tokenIds: BigNumberish[],
    amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    token: string,
    recipient: string,
    tokenIds: bigint[],
    amounts: bigint[]
  ];
  export interface OutputObject {
    token: string;
    recipient: string;
    tokenIds: bigint[];
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositERC1155Event {
  export type InputTuple = [
    _l1Token: AddressLike,
    _l2Token: AddressLike,
    _from: AddressLike,
    _to: AddressLike,
    _tokenId: BigNumberish,
    _amount: BigNumberish
  ];
  export type OutputTuple = [
    _l1Token: string,
    _l2Token: string,
    _from: string,
    _to: string,
    _tokenId: bigint,
    _amount: bigint
  ];
  export interface OutputObject {
    _l1Token: string;
    _l2Token: string;
    _from: string;
    _to: string;
    _tokenId: bigint;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeBatchWithdrawERC1155Event {
  export type InputTuple = [
    _l1Token: AddressLike,
    _l2Token: AddressLike,
    _from: AddressLike,
    _to: AddressLike,
    _tokenIds: BigNumberish[],
    _amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    _l1Token: string,
    _l2Token: string,
    _from: string,
    _to: string,
    _tokenIds: bigint[],
    _amounts: bigint[]
  ];
  export interface OutputObject {
    _l1Token: string;
    _l2Token: string;
    _from: string;
    _to: string;
    _tokenIds: bigint[];
    _amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeWithdrawERC1155Event {
  export type InputTuple = [
    _l1Token: AddressLike,
    _l2Token: AddressLike,
    _from: AddressLike,
    _to: AddressLike,
    _tokenId: BigNumberish,
    _amount: BigNumberish
  ];
  export type OutputTuple = [
    _l1Token: string,
    _l2Token: string,
    _from: string,
    _to: string,
    _tokenId: bigint,
    _amount: bigint
  ];
  export interface OutputObject {
    _l1Token: string;
    _l2Token: string;
    _from: string;
    _to: string;
    _tokenId: bigint;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundERC1155Event {
  export type InputTuple = [
    token: AddressLike,
    recipient: AddressLike,
    tokenId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    recipient: string,
    tokenId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    recipient: string;
    tokenId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateTokenMappingEvent {
  export type InputTuple = [
    l1Token: AddressLike,
    oldL2Token: AddressLike,
    newL2Token: AddressLike
  ];
  export type OutputTuple = [
    l1Token: string,
    oldL2Token: string,
    newL2Token: string
  ];
  export interface OutputObject {
    l1Token: string;
    oldL2Token: string;
    newL2Token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface L1ERC1155Gateway extends BaseContract {
  connect(runner?: ContractRunner | null): L1ERC1155Gateway;
  waitForDeployment(): Promise<this>;

  interface: L1ERC1155GatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "batchDepositERC1155(address,uint256[],uint256[],uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  "batchDepositERC1155(address,address,uint256[],uint256[],uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  counterpart: TypedContractMethod<[], [string], "view">;

  "depositERC1155(address,address,uint256,uint256,uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  "depositERC1155(address,uint256,uint256,uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  finalizeBatchWithdrawERC1155: TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  finalizeWithdrawERC1155: TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [_counterpart: AddressLike, _messenger: AddressLike],
    [void],
    "nonpayable"
  >;

  messenger: TypedContractMethod<[], [string], "view">;

  onDropMessage: TypedContractMethod<[_message: BytesLike], [void], "payable">;

  onERC1155BatchReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  router: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tokenMapping: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTokenMapping: TypedContractMethod<
    [_l1Token: AddressLike, _l2Token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchDepositERC1155(address,uint256[],uint256[],uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "batchDepositERC1155(address,address,uint256[],uint256[],uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "counterpart"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositERC1155(address,address,uint256,uint256,uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositERC1155(address,uint256,uint256,uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeBatchWithdrawERC1155"
  ): TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdrawERC1155"
  ): TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_counterpart: AddressLike, _messenger: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "messenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onDropMessage"
  ): TypedContractMethod<[_message: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenMapping"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTokenMapping"
  ): TypedContractMethod<
    [_l1Token: AddressLike, _l2Token: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchDepositERC1155"
  ): TypedContractEvent<
    BatchDepositERC1155Event.InputTuple,
    BatchDepositERC1155Event.OutputTuple,
    BatchDepositERC1155Event.OutputObject
  >;
  getEvent(
    key: "BatchRefundERC1155"
  ): TypedContractEvent<
    BatchRefundERC1155Event.InputTuple,
    BatchRefundERC1155Event.OutputTuple,
    BatchRefundERC1155Event.OutputObject
  >;
  getEvent(
    key: "DepositERC1155"
  ): TypedContractEvent<
    DepositERC1155Event.InputTuple,
    DepositERC1155Event.OutputTuple,
    DepositERC1155Event.OutputObject
  >;
  getEvent(
    key: "FinalizeBatchWithdrawERC1155"
  ): TypedContractEvent<
    FinalizeBatchWithdrawERC1155Event.InputTuple,
    FinalizeBatchWithdrawERC1155Event.OutputTuple,
    FinalizeBatchWithdrawERC1155Event.OutputObject
  >;
  getEvent(
    key: "FinalizeWithdrawERC1155"
  ): TypedContractEvent<
    FinalizeWithdrawERC1155Event.InputTuple,
    FinalizeWithdrawERC1155Event.OutputTuple,
    FinalizeWithdrawERC1155Event.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefundERC1155"
  ): TypedContractEvent<
    RefundERC1155Event.InputTuple,
    RefundERC1155Event.OutputTuple,
    RefundERC1155Event.OutputObject
  >;
  getEvent(
    key: "UpdateTokenMapping"
  ): TypedContractEvent<
    UpdateTokenMappingEvent.InputTuple,
    UpdateTokenMappingEvent.OutputTuple,
    UpdateTokenMappingEvent.OutputObject
  >;

  filters: {
    "BatchDepositERC1155(address,address,address,address,uint256[],uint256[])": TypedContractEvent<
      BatchDepositERC1155Event.InputTuple,
      BatchDepositERC1155Event.OutputTuple,
      BatchDepositERC1155Event.OutputObject
    >;
    BatchDepositERC1155: TypedContractEvent<
      BatchDepositERC1155Event.InputTuple,
      BatchDepositERC1155Event.OutputTuple,
      BatchDepositERC1155Event.OutputObject
    >;

    "BatchRefundERC1155(address,address,uint256[],uint256[])": TypedContractEvent<
      BatchRefundERC1155Event.InputTuple,
      BatchRefundERC1155Event.OutputTuple,
      BatchRefundERC1155Event.OutputObject
    >;
    BatchRefundERC1155: TypedContractEvent<
      BatchRefundERC1155Event.InputTuple,
      BatchRefundERC1155Event.OutputTuple,
      BatchRefundERC1155Event.OutputObject
    >;

    "DepositERC1155(address,address,address,address,uint256,uint256)": TypedContractEvent<
      DepositERC1155Event.InputTuple,
      DepositERC1155Event.OutputTuple,
      DepositERC1155Event.OutputObject
    >;
    DepositERC1155: TypedContractEvent<
      DepositERC1155Event.InputTuple,
      DepositERC1155Event.OutputTuple,
      DepositERC1155Event.OutputObject
    >;

    "FinalizeBatchWithdrawERC1155(address,address,address,address,uint256[],uint256[])": TypedContractEvent<
      FinalizeBatchWithdrawERC1155Event.InputTuple,
      FinalizeBatchWithdrawERC1155Event.OutputTuple,
      FinalizeBatchWithdrawERC1155Event.OutputObject
    >;
    FinalizeBatchWithdrawERC1155: TypedContractEvent<
      FinalizeBatchWithdrawERC1155Event.InputTuple,
      FinalizeBatchWithdrawERC1155Event.OutputTuple,
      FinalizeBatchWithdrawERC1155Event.OutputObject
    >;

    "FinalizeWithdrawERC1155(address,address,address,address,uint256,uint256)": TypedContractEvent<
      FinalizeWithdrawERC1155Event.InputTuple,
      FinalizeWithdrawERC1155Event.OutputTuple,
      FinalizeWithdrawERC1155Event.OutputObject
    >;
    FinalizeWithdrawERC1155: TypedContractEvent<
      FinalizeWithdrawERC1155Event.InputTuple,
      FinalizeWithdrawERC1155Event.OutputTuple,
      FinalizeWithdrawERC1155Event.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefundERC1155(address,address,uint256,uint256)": TypedContractEvent<
      RefundERC1155Event.InputTuple,
      RefundERC1155Event.OutputTuple,
      RefundERC1155Event.OutputObject
    >;
    RefundERC1155: TypedContractEvent<
      RefundERC1155Event.InputTuple,
      RefundERC1155Event.OutputTuple,
      RefundERC1155Event.OutputObject
    >;

    "UpdateTokenMapping(address,address,address)": TypedContractEvent<
      UpdateTokenMappingEvent.InputTuple,
      UpdateTokenMappingEvent.OutputTuple,
      UpdateTokenMappingEvent.OutputObject
    >;
    UpdateTokenMapping: TypedContractEvent<
      UpdateTokenMappingEvent.InputTuple,
      UpdateTokenMappingEvent.OutputTuple,
      UpdateTokenMappingEvent.OutputObject
    >;
  };
}
