/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface L2ERC721GatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchWithdrawERC721(address,uint256[],uint256)"
      | "batchWithdrawERC721(address,address,uint256[],uint256)"
      | "counterpart"
      | "finalizeBatchDepositERC721"
      | "finalizeDepositERC721"
      | "initialize"
      | "messenger"
      | "onERC721Received"
      | "owner"
      | "renounceOwnership"
      | "router"
      | "tokenMapping"
      | "transferOwnership"
      | "updateTokenMapping"
      | "withdrawERC721(address,uint256,uint256)"
      | "withdrawERC721(address,address,uint256,uint256)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchWithdrawERC721"
      | "FinalizeBatchDepositERC721"
      | "FinalizeDepositERC721"
      | "Initialized"
      | "OwnershipTransferred"
      | "UpdateTokenMapping"
      | "WithdrawERC721"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchWithdrawERC721(address,uint256[],uint256)",
    values: [AddressLike, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWithdrawERC721(address,address,uint256[],uint256)",
    values: [AddressLike, AddressLike, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "counterpart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBatchDepositERC721",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDepositERC721",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "messenger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenMapping",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenMapping",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC721(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC721(address,address,uint256,uint256)",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchWithdrawERC721(address,uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchWithdrawERC721(address,address,uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterpart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBatchDepositERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDepositERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messenger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC721(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC721(address,address,uint256,uint256)",
    data: BytesLike
  ): Result;
}

export namespace BatchWithdrawERC721Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    tokenIds: BigNumberish[]
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    tokenIds: bigint[]
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    tokenIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeBatchDepositERC721Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    tokenIds: BigNumberish[]
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    tokenIds: bigint[]
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    tokenIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeDepositERC721Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateTokenMappingEvent {
  export type InputTuple = [
    l2Token: AddressLike,
    oldL1Token: AddressLike,
    newL1Token: AddressLike
  ];
  export type OutputTuple = [
    l2Token: string,
    oldL1Token: string,
    newL1Token: string
  ];
  export interface OutputObject {
    l2Token: string;
    oldL1Token: string;
    newL1Token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawERC721Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface L2ERC721Gateway extends BaseContract {
  connect(runner?: ContractRunner | null): L2ERC721Gateway;
  waitForDeployment(): Promise<this>;

  interface: L2ERC721GatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "batchWithdrawERC721(address,uint256[],uint256)": TypedContractMethod<
    [_token: AddressLike, _tokenIds: BigNumberish[], _gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  "batchWithdrawERC721(address,address,uint256[],uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  counterpart: TypedContractMethod<[], [string], "view">;

  finalizeBatchDepositERC721: TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  finalizeDepositERC721: TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [_counterpart: AddressLike, _messenger: AddressLike],
    [void],
    "nonpayable"
  >;

  messenger: TypedContractMethod<[], [string], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  router: TypedContractMethod<[], [string], "view">;

  tokenMapping: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTokenMapping: TypedContractMethod<
    [_l2Token: AddressLike, _l1Token: AddressLike],
    [void],
    "nonpayable"
  >;

  "withdrawERC721(address,uint256,uint256)": TypedContractMethod<
    [_token: AddressLike, _tokenId: BigNumberish, _gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  "withdrawERC721(address,address,uint256,uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchWithdrawERC721(address,uint256[],uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _tokenIds: BigNumberish[], _gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "batchWithdrawERC721(address,address,uint256[],uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[],
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "counterpart"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeBatchDepositERC721"
  ): TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeDepositERC721"
  ): TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_counterpart: AddressLike, _messenger: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "messenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenMapping"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTokenMapping"
  ): TypedContractMethod<
    [_l2Token: AddressLike, _l1Token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawERC721(address,uint256,uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _tokenId: BigNumberish, _gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawERC721(address,address,uint256,uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _tokenId: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "BatchWithdrawERC721"
  ): TypedContractEvent<
    BatchWithdrawERC721Event.InputTuple,
    BatchWithdrawERC721Event.OutputTuple,
    BatchWithdrawERC721Event.OutputObject
  >;
  getEvent(
    key: "FinalizeBatchDepositERC721"
  ): TypedContractEvent<
    FinalizeBatchDepositERC721Event.InputTuple,
    FinalizeBatchDepositERC721Event.OutputTuple,
    FinalizeBatchDepositERC721Event.OutputObject
  >;
  getEvent(
    key: "FinalizeDepositERC721"
  ): TypedContractEvent<
    FinalizeDepositERC721Event.InputTuple,
    FinalizeDepositERC721Event.OutputTuple,
    FinalizeDepositERC721Event.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdateTokenMapping"
  ): TypedContractEvent<
    UpdateTokenMappingEvent.InputTuple,
    UpdateTokenMappingEvent.OutputTuple,
    UpdateTokenMappingEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawERC721"
  ): TypedContractEvent<
    WithdrawERC721Event.InputTuple,
    WithdrawERC721Event.OutputTuple,
    WithdrawERC721Event.OutputObject
  >;

  filters: {
    "BatchWithdrawERC721(address,address,address,address,uint256[])": TypedContractEvent<
      BatchWithdrawERC721Event.InputTuple,
      BatchWithdrawERC721Event.OutputTuple,
      BatchWithdrawERC721Event.OutputObject
    >;
    BatchWithdrawERC721: TypedContractEvent<
      BatchWithdrawERC721Event.InputTuple,
      BatchWithdrawERC721Event.OutputTuple,
      BatchWithdrawERC721Event.OutputObject
    >;

    "FinalizeBatchDepositERC721(address,address,address,address,uint256[])": TypedContractEvent<
      FinalizeBatchDepositERC721Event.InputTuple,
      FinalizeBatchDepositERC721Event.OutputTuple,
      FinalizeBatchDepositERC721Event.OutputObject
    >;
    FinalizeBatchDepositERC721: TypedContractEvent<
      FinalizeBatchDepositERC721Event.InputTuple,
      FinalizeBatchDepositERC721Event.OutputTuple,
      FinalizeBatchDepositERC721Event.OutputObject
    >;

    "FinalizeDepositERC721(address,address,address,address,uint256)": TypedContractEvent<
      FinalizeDepositERC721Event.InputTuple,
      FinalizeDepositERC721Event.OutputTuple,
      FinalizeDepositERC721Event.OutputObject
    >;
    FinalizeDepositERC721: TypedContractEvent<
      FinalizeDepositERC721Event.InputTuple,
      FinalizeDepositERC721Event.OutputTuple,
      FinalizeDepositERC721Event.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdateTokenMapping(address,address,address)": TypedContractEvent<
      UpdateTokenMappingEvent.InputTuple,
      UpdateTokenMappingEvent.OutputTuple,
      UpdateTokenMappingEvent.OutputObject
    >;
    UpdateTokenMapping: TypedContractEvent<
      UpdateTokenMappingEvent.InputTuple,
      UpdateTokenMappingEvent.OutputTuple,
      UpdateTokenMappingEvent.OutputObject
    >;

    "WithdrawERC721(address,address,address,address,uint256)": TypedContractEvent<
      WithdrawERC721Event.InputTuple,
      WithdrawERC721Event.OutputTuple,
      WithdrawERC721Event.OutputObject
    >;
    WithdrawERC721: TypedContractEvent<
      WithdrawERC721Event.InputTuple,
      WithdrawERC721Event.OutputTuple,
      WithdrawERC721Event.OutputObject
    >;
  };
}
