/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1271Upgradeable__factory } from "./IERC1271Upgradeable__factory";
export { IERC5267Upgradeable__factory } from "./IERC5267Upgradeable__factory";
