/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL2GasPriceOracle,
  IL2GasPriceOracleInterface,
} from "../../../../src/L1/rollup/IL2GasPriceOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
    ],
    name: "calculateIntrinsicGasFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_gasLimit",
        type: "uint256",
      },
    ],
    name: "estimateCrossDomainMessageFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "l2BaseFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "whitelist",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL2GasPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IL2GasPriceOracleInterface {
    return new Interface(_abi) as IL2GasPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IL2GasPriceOracle {
    return new Contract(address, _abi, runner) as unknown as IL2GasPriceOracle;
  }
}
