/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface L1MessageQueueWithGasPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appendCrossDomainMessage"
      | "appendEnforcedTransaction"
      | "calculateIntrinsicGasFee"
      | "computeTransactionHash"
      | "dropCrossDomainMessage"
      | "enforcedTxGateway"
      | "estimateCrossDomainMessageFee"
      | "gasOracle"
      | "getCrossDomainMessage"
      | "initialize"
      | "initializeV2"
      | "isMessageDropped"
      | "isMessageSkipped"
      | "l2BaseFee"
      | "maxGasLimit"
      | "messageQueue"
      | "messenger"
      | "nextCrossDomainMessageIndex"
      | "owner"
      | "pendingQueueIndex"
      | "popCrossDomainMessage"
      | "renounceOwnership"
      | "scrollChain"
      | "setL2BaseFee"
      | "transferOwnership"
      | "updateGasOracle"
      | "updateMaxGasLimit"
      | "updateWhitelistChecker"
      | "whitelistChecker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DequeueTransaction"
      | "DropTransaction"
      | "Initialized"
      | "OwnershipTransferred"
      | "QueueTransaction"
      | "UpdateGasOracle"
      | "UpdateL2BaseFee"
      | "UpdateMaxGasLimit"
      | "UpdateWhitelistChecker"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "appendCrossDomainMessage",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "appendEnforcedTransaction",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateIntrinsicGasFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeTransactionHash",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dropCrossDomainMessage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enforcedTxGateway",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimateCrossDomainMessageFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gasOracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCrossDomainMessage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMessageDropped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMessageSkipped",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "l2BaseFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageQueue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "messenger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextCrossDomainMessageIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingQueueIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "popCrossDomainMessage",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scrollChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setL2BaseFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGasOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelistChecker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistChecker",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "appendCrossDomainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appendEnforcedTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateIntrinsicGasFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeTransactionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropCrossDomainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforcedTxGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateCrossDomainMessageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCrossDomainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMessageDropped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMessageSkipped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l2BaseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messenger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCrossDomainMessageIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingQueueIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "popCrossDomainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scrollChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setL2BaseFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGasOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelistChecker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistChecker",
    data: BytesLike
  ): Result;
}

export namespace DequeueTransactionEvent {
  export type InputTuple = [
    startIndex: BigNumberish,
    count: BigNumberish,
    skippedBitmap: BigNumberish
  ];
  export type OutputTuple = [
    startIndex: bigint,
    count: bigint,
    skippedBitmap: bigint
  ];
  export interface OutputObject {
    startIndex: bigint;
    count: bigint;
    skippedBitmap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DropTransactionEvent {
  export type InputTuple = [index: BigNumberish];
  export type OutputTuple = [index: bigint];
  export interface OutputObject {
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueueTransactionEvent {
  export type InputTuple = [
    sender: AddressLike,
    target: AddressLike,
    value: BigNumberish,
    queueIndex: BigNumberish,
    gasLimit: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    target: string,
    value: bigint,
    queueIndex: bigint,
    gasLimit: bigint,
    data: string
  ];
  export interface OutputObject {
    sender: string;
    target: string;
    value: bigint;
    queueIndex: bigint;
    gasLimit: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateGasOracleEvent {
  export type InputTuple = [
    _oldGasOracle: AddressLike,
    _newGasOracle: AddressLike
  ];
  export type OutputTuple = [_oldGasOracle: string, _newGasOracle: string];
  export interface OutputObject {
    _oldGasOracle: string;
    _newGasOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateL2BaseFeeEvent {
  export type InputTuple = [
    oldL2BaseFee: BigNumberish,
    newL2BaseFee: BigNumberish
  ];
  export type OutputTuple = [oldL2BaseFee: bigint, newL2BaseFee: bigint];
  export interface OutputObject {
    oldL2BaseFee: bigint;
    newL2BaseFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateMaxGasLimitEvent {
  export type InputTuple = [
    _oldMaxGasLimit: BigNumberish,
    _newMaxGasLimit: BigNumberish
  ];
  export type OutputTuple = [_oldMaxGasLimit: bigint, _newMaxGasLimit: bigint];
  export interface OutputObject {
    _oldMaxGasLimit: bigint;
    _newMaxGasLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateWhitelistCheckerEvent {
  export type InputTuple = [
    _oldWhitelistChecker: AddressLike,
    _newWhitelistChecker: AddressLike
  ];
  export type OutputTuple = [
    _oldWhitelistChecker: string,
    _newWhitelistChecker: string
  ];
  export interface OutputObject {
    _oldWhitelistChecker: string;
    _newWhitelistChecker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface L1MessageQueueWithGasPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): L1MessageQueueWithGasPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: L1MessageQueueWithGasPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appendCrossDomainMessage: TypedContractMethod<
    [_target: AddressLike, _gasLimit: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  appendEnforcedTransaction: TypedContractMethod<
    [
      _sender: AddressLike,
      _target: AddressLike,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  calculateIntrinsicGasFee: TypedContractMethod<
    [_calldata: BytesLike],
    [bigint],
    "view"
  >;

  computeTransactionHash: TypedContractMethod<
    [
      _sender: AddressLike,
      _queueIndex: BigNumberish,
      _value: BigNumberish,
      _target: AddressLike,
      _gasLimit: BigNumberish,
      _data: BytesLike
    ],
    [string],
    "view"
  >;

  dropCrossDomainMessage: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  enforcedTxGateway: TypedContractMethod<[], [string], "view">;

  estimateCrossDomainMessageFee: TypedContractMethod<
    [_gasLimit: BigNumberish],
    [bigint],
    "view"
  >;

  gasOracle: TypedContractMethod<[], [string], "view">;

  getCrossDomainMessage: TypedContractMethod<
    [_queueIndex: BigNumberish],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _messenger: AddressLike,
      _scrollChain: AddressLike,
      _enforcedTxGateway: AddressLike,
      _gasOracle: AddressLike,
      _maxGasLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  initializeV2: TypedContractMethod<[], [void], "nonpayable">;

  isMessageDropped: TypedContractMethod<
    [_queueIndex: BigNumberish],
    [boolean],
    "view"
  >;

  isMessageSkipped: TypedContractMethod<
    [_queueIndex: BigNumberish],
    [boolean],
    "view"
  >;

  l2BaseFee: TypedContractMethod<[], [bigint], "view">;

  maxGasLimit: TypedContractMethod<[], [bigint], "view">;

  messageQueue: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  messenger: TypedContractMethod<[], [string], "view">;

  nextCrossDomainMessageIndex: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingQueueIndex: TypedContractMethod<[], [bigint], "view">;

  popCrossDomainMessage: TypedContractMethod<
    [
      _startIndex: BigNumberish,
      _count: BigNumberish,
      _skippedBitmap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scrollChain: TypedContractMethod<[], [string], "view">;

  setL2BaseFee: TypedContractMethod<
    [_newL2BaseFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGasOracle: TypedContractMethod<
    [_newGasOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  updateMaxGasLimit: TypedContractMethod<
    [_newMaxGasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWhitelistChecker: TypedContractMethod<
    [_newWhitelistChecker: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelistChecker: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appendCrossDomainMessage"
  ): TypedContractMethod<
    [_target: AddressLike, _gasLimit: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "appendEnforcedTransaction"
  ): TypedContractMethod<
    [
      _sender: AddressLike,
      _target: AddressLike,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateIntrinsicGasFee"
  ): TypedContractMethod<[_calldata: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeTransactionHash"
  ): TypedContractMethod<
    [
      _sender: AddressLike,
      _queueIndex: BigNumberish,
      _value: BigNumberish,
      _target: AddressLike,
      _gasLimit: BigNumberish,
      _data: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dropCrossDomainMessage"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enforcedTxGateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "estimateCrossDomainMessageFee"
  ): TypedContractMethod<[_gasLimit: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCrossDomainMessage"
  ): TypedContractMethod<[_queueIndex: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _messenger: AddressLike,
      _scrollChain: AddressLike,
      _enforcedTxGateway: AddressLike,
      _gasOracle: AddressLike,
      _maxGasLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeV2"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isMessageDropped"
  ): TypedContractMethod<[_queueIndex: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMessageSkipped"
  ): TypedContractMethod<[_queueIndex: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "l2BaseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageQueue"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "messenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextCrossDomainMessageIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingQueueIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "popCrossDomainMessage"
  ): TypedContractMethod<
    [
      _startIndex: BigNumberish,
      _count: BigNumberish,
      _skippedBitmap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scrollChain"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setL2BaseFee"
  ): TypedContractMethod<[_newL2BaseFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGasOracle"
  ): TypedContractMethod<[_newGasOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMaxGasLimit"
  ): TypedContractMethod<[_newMaxGasLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelistChecker"
  ): TypedContractMethod<
    [_newWhitelistChecker: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistChecker"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DequeueTransaction"
  ): TypedContractEvent<
    DequeueTransactionEvent.InputTuple,
    DequeueTransactionEvent.OutputTuple,
    DequeueTransactionEvent.OutputObject
  >;
  getEvent(
    key: "DropTransaction"
  ): TypedContractEvent<
    DropTransactionEvent.InputTuple,
    DropTransactionEvent.OutputTuple,
    DropTransactionEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QueueTransaction"
  ): TypedContractEvent<
    QueueTransactionEvent.InputTuple,
    QueueTransactionEvent.OutputTuple,
    QueueTransactionEvent.OutputObject
  >;
  getEvent(
    key: "UpdateGasOracle"
  ): TypedContractEvent<
    UpdateGasOracleEvent.InputTuple,
    UpdateGasOracleEvent.OutputTuple,
    UpdateGasOracleEvent.OutputObject
  >;
  getEvent(
    key: "UpdateL2BaseFee"
  ): TypedContractEvent<
    UpdateL2BaseFeeEvent.InputTuple,
    UpdateL2BaseFeeEvent.OutputTuple,
    UpdateL2BaseFeeEvent.OutputObject
  >;
  getEvent(
    key: "UpdateMaxGasLimit"
  ): TypedContractEvent<
    UpdateMaxGasLimitEvent.InputTuple,
    UpdateMaxGasLimitEvent.OutputTuple,
    UpdateMaxGasLimitEvent.OutputObject
  >;
  getEvent(
    key: "UpdateWhitelistChecker"
  ): TypedContractEvent<
    UpdateWhitelistCheckerEvent.InputTuple,
    UpdateWhitelistCheckerEvent.OutputTuple,
    UpdateWhitelistCheckerEvent.OutputObject
  >;

  filters: {
    "DequeueTransaction(uint256,uint256,uint256)": TypedContractEvent<
      DequeueTransactionEvent.InputTuple,
      DequeueTransactionEvent.OutputTuple,
      DequeueTransactionEvent.OutputObject
    >;
    DequeueTransaction: TypedContractEvent<
      DequeueTransactionEvent.InputTuple,
      DequeueTransactionEvent.OutputTuple,
      DequeueTransactionEvent.OutputObject
    >;

    "DropTransaction(uint256)": TypedContractEvent<
      DropTransactionEvent.InputTuple,
      DropTransactionEvent.OutputTuple,
      DropTransactionEvent.OutputObject
    >;
    DropTransaction: TypedContractEvent<
      DropTransactionEvent.InputTuple,
      DropTransactionEvent.OutputTuple,
      DropTransactionEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QueueTransaction(address,address,uint256,uint64,uint256,bytes)": TypedContractEvent<
      QueueTransactionEvent.InputTuple,
      QueueTransactionEvent.OutputTuple,
      QueueTransactionEvent.OutputObject
    >;
    QueueTransaction: TypedContractEvent<
      QueueTransactionEvent.InputTuple,
      QueueTransactionEvent.OutputTuple,
      QueueTransactionEvent.OutputObject
    >;

    "UpdateGasOracle(address,address)": TypedContractEvent<
      UpdateGasOracleEvent.InputTuple,
      UpdateGasOracleEvent.OutputTuple,
      UpdateGasOracleEvent.OutputObject
    >;
    UpdateGasOracle: TypedContractEvent<
      UpdateGasOracleEvent.InputTuple,
      UpdateGasOracleEvent.OutputTuple,
      UpdateGasOracleEvent.OutputObject
    >;

    "UpdateL2BaseFee(uint256,uint256)": TypedContractEvent<
      UpdateL2BaseFeeEvent.InputTuple,
      UpdateL2BaseFeeEvent.OutputTuple,
      UpdateL2BaseFeeEvent.OutputObject
    >;
    UpdateL2BaseFee: TypedContractEvent<
      UpdateL2BaseFeeEvent.InputTuple,
      UpdateL2BaseFeeEvent.OutputTuple,
      UpdateL2BaseFeeEvent.OutputObject
    >;

    "UpdateMaxGasLimit(uint256,uint256)": TypedContractEvent<
      UpdateMaxGasLimitEvent.InputTuple,
      UpdateMaxGasLimitEvent.OutputTuple,
      UpdateMaxGasLimitEvent.OutputObject
    >;
    UpdateMaxGasLimit: TypedContractEvent<
      UpdateMaxGasLimitEvent.InputTuple,
      UpdateMaxGasLimitEvent.OutputTuple,
      UpdateMaxGasLimitEvent.OutputObject
    >;

    "UpdateWhitelistChecker(address,address)": TypedContractEvent<
      UpdateWhitelistCheckerEvent.InputTuple,
      UpdateWhitelistCheckerEvent.OutputTuple,
      UpdateWhitelistCheckerEvent.OutputObject
    >;
    UpdateWhitelistChecker: TypedContractEvent<
      UpdateWhitelistCheckerEvent.InputTuple,
      UpdateWhitelistCheckerEvent.OutputTuple,
      UpdateWhitelistCheckerEvent.OutputObject
    >;
  };
}
