/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFiatToken,
  IFiatTokenInterface,
} from "../../../src/interfaces/IFiatToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFiatToken__factory {
  static readonly abi = _abi;
  static createInterface(): IFiatTokenInterface {
    return new Interface(_abi) as IFiatTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFiatToken {
    return new Contract(address, _abi, runner) as unknown as IFiatToken;
  }
}
