/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IL1GatewayRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositERC20(address,uint256,uint256)"
      | "depositERC20(address,address,uint256,uint256)"
      | "depositERC20AndCall"
      | "depositETH(uint256,uint256)"
      | "depositETH(address,uint256,uint256)"
      | "depositETHAndCall"
      | "finalizeWithdrawERC20"
      | "finalizeWithdrawETH"
      | "getERC20Gateway"
      | "getL2ERC20Address"
      | "requestERC20"
      | "setDefaultERC20Gateway"
      | "setERC20Gateway"
      | "setETHGateway"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositERC20"
      | "DepositETH"
      | "FinalizeWithdrawERC20"
      | "FinalizeWithdrawETH"
      | "RefundERC20"
      | "RefundETH"
      | "SetDefaultERC20Gateway"
      | "SetERC20Gateway"
      | "SetETHGateway"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositERC20(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20(address,address,uint256,uint256)",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20AndCall",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETHAndCall",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawERC20",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawETH",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getERC20Gateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getL2ERC20Address",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultERC20Gateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setERC20Gateway",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setETHGateway",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositERC20(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20(address,address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20AndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositETH(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositETH(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositETHAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC20Gateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getL2ERC20Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultERC20Gateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setERC20Gateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setETHGateway",
    data: BytesLike
  ): Result;
}

export namespace DepositERC20Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    amount: bigint,
    data: string
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositETHEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    data: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeWithdrawERC20Event {
  export type InputTuple = [
    l1Token: AddressLike,
    l2Token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    l1Token: string,
    l2Token: string,
    from: string,
    to: string,
    amount: bigint,
    data: string
  ];
  export interface OutputObject {
    l1Token: string;
    l2Token: string;
    from: string;
    to: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeWithdrawETHEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    data: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundERC20Event {
  export type InputTuple = [
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, recipient: string, amount: bigint];
  export interface OutputObject {
    token: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundETHEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetDefaultERC20GatewayEvent {
  export type InputTuple = [
    oldDefaultERC20Gateway: AddressLike,
    newDefaultERC20Gateway: AddressLike
  ];
  export type OutputTuple = [
    oldDefaultERC20Gateway: string,
    newDefaultERC20Gateway: string
  ];
  export interface OutputObject {
    oldDefaultERC20Gateway: string;
    newDefaultERC20Gateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetERC20GatewayEvent {
  export type InputTuple = [
    token: AddressLike,
    oldGateway: AddressLike,
    newGateway: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    oldGateway: string,
    newGateway: string
  ];
  export interface OutputObject {
    token: string;
    oldGateway: string;
    newGateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetETHGatewayEvent {
  export type InputTuple = [
    oldETHGateway: AddressLike,
    newEthGateway: AddressLike
  ];
  export type OutputTuple = [oldETHGateway: string, newEthGateway: string];
  export interface OutputObject {
    oldETHGateway: string;
    newEthGateway: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IL1GatewayRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IL1GatewayRouter;
  waitForDeployment(): Promise<this>;

  interface: IL1GatewayRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "depositERC20(address,uint256,uint256)": TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish, _gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  "depositERC20(address,address,uint256,uint256)": TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  depositERC20AndCall: TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  "depositETH(uint256,uint256)": TypedContractMethod<
    [amount: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  "depositETH(address,uint256,uint256)": TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  depositETHAndCall: TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike,
      gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;

  finalizeWithdrawERC20: TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "payable"
  >;

  finalizeWithdrawETH: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "payable"
  >;

  getERC20Gateway: TypedContractMethod<[_token: AddressLike], [string], "view">;

  getL2ERC20Address: TypedContractMethod<
    [_l1Token: AddressLike],
    [string],
    "view"
  >;

  requestERC20: TypedContractMethod<
    [sender: AddressLike, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  setDefaultERC20Gateway: TypedContractMethod<
    [_defaultERC20Gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  setERC20Gateway: TypedContractMethod<
    [_tokens: AddressLike[], _gateways: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setETHGateway: TypedContractMethod<
    [_ethGateway: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositERC20(address,uint256,uint256)"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish, _gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositERC20(address,address,uint256,uint256)"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositERC20AndCall"
  ): TypedContractMethod<
    [
      _token: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike,
      _gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositETH(uint256,uint256)"
  ): TypedContractMethod<
    [amount: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositETH(address,uint256,uint256)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositETHAndCall"
  ): TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike,
      gasLimit: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdrawERC20"
  ): TypedContractMethod<
    [
      _l1Token: AddressLike,
      _l2Token: AddressLike,
      _from: AddressLike,
      _to: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdrawETH"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getERC20Gateway"
  ): TypedContractMethod<[_token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getL2ERC20Address"
  ): TypedContractMethod<[_l1Token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "requestERC20"
  ): TypedContractMethod<
    [sender: AddressLike, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultERC20Gateway"
  ): TypedContractMethod<
    [_defaultERC20Gateway: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setERC20Gateway"
  ): TypedContractMethod<
    [_tokens: AddressLike[], _gateways: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setETHGateway"
  ): TypedContractMethod<[_ethGateway: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DepositERC20"
  ): TypedContractEvent<
    DepositERC20Event.InputTuple,
    DepositERC20Event.OutputTuple,
    DepositERC20Event.OutputObject
  >;
  getEvent(
    key: "DepositETH"
  ): TypedContractEvent<
    DepositETHEvent.InputTuple,
    DepositETHEvent.OutputTuple,
    DepositETHEvent.OutputObject
  >;
  getEvent(
    key: "FinalizeWithdrawERC20"
  ): TypedContractEvent<
    FinalizeWithdrawERC20Event.InputTuple,
    FinalizeWithdrawERC20Event.OutputTuple,
    FinalizeWithdrawERC20Event.OutputObject
  >;
  getEvent(
    key: "FinalizeWithdrawETH"
  ): TypedContractEvent<
    FinalizeWithdrawETHEvent.InputTuple,
    FinalizeWithdrawETHEvent.OutputTuple,
    FinalizeWithdrawETHEvent.OutputObject
  >;
  getEvent(
    key: "RefundERC20"
  ): TypedContractEvent<
    RefundERC20Event.InputTuple,
    RefundERC20Event.OutputTuple,
    RefundERC20Event.OutputObject
  >;
  getEvent(
    key: "RefundETH"
  ): TypedContractEvent<
    RefundETHEvent.InputTuple,
    RefundETHEvent.OutputTuple,
    RefundETHEvent.OutputObject
  >;
  getEvent(
    key: "SetDefaultERC20Gateway"
  ): TypedContractEvent<
    SetDefaultERC20GatewayEvent.InputTuple,
    SetDefaultERC20GatewayEvent.OutputTuple,
    SetDefaultERC20GatewayEvent.OutputObject
  >;
  getEvent(
    key: "SetERC20Gateway"
  ): TypedContractEvent<
    SetERC20GatewayEvent.InputTuple,
    SetERC20GatewayEvent.OutputTuple,
    SetERC20GatewayEvent.OutputObject
  >;
  getEvent(
    key: "SetETHGateway"
  ): TypedContractEvent<
    SetETHGatewayEvent.InputTuple,
    SetETHGatewayEvent.OutputTuple,
    SetETHGatewayEvent.OutputObject
  >;

  filters: {
    "DepositERC20(address,address,address,address,uint256,bytes)": TypedContractEvent<
      DepositERC20Event.InputTuple,
      DepositERC20Event.OutputTuple,
      DepositERC20Event.OutputObject
    >;
    DepositERC20: TypedContractEvent<
      DepositERC20Event.InputTuple,
      DepositERC20Event.OutputTuple,
      DepositERC20Event.OutputObject
    >;

    "DepositETH(address,address,uint256,bytes)": TypedContractEvent<
      DepositETHEvent.InputTuple,
      DepositETHEvent.OutputTuple,
      DepositETHEvent.OutputObject
    >;
    DepositETH: TypedContractEvent<
      DepositETHEvent.InputTuple,
      DepositETHEvent.OutputTuple,
      DepositETHEvent.OutputObject
    >;

    "FinalizeWithdrawERC20(address,address,address,address,uint256,bytes)": TypedContractEvent<
      FinalizeWithdrawERC20Event.InputTuple,
      FinalizeWithdrawERC20Event.OutputTuple,
      FinalizeWithdrawERC20Event.OutputObject
    >;
    FinalizeWithdrawERC20: TypedContractEvent<
      FinalizeWithdrawERC20Event.InputTuple,
      FinalizeWithdrawERC20Event.OutputTuple,
      FinalizeWithdrawERC20Event.OutputObject
    >;

    "FinalizeWithdrawETH(address,address,uint256,bytes)": TypedContractEvent<
      FinalizeWithdrawETHEvent.InputTuple,
      FinalizeWithdrawETHEvent.OutputTuple,
      FinalizeWithdrawETHEvent.OutputObject
    >;
    FinalizeWithdrawETH: TypedContractEvent<
      FinalizeWithdrawETHEvent.InputTuple,
      FinalizeWithdrawETHEvent.OutputTuple,
      FinalizeWithdrawETHEvent.OutputObject
    >;

    "RefundERC20(address,address,uint256)": TypedContractEvent<
      RefundERC20Event.InputTuple,
      RefundERC20Event.OutputTuple,
      RefundERC20Event.OutputObject
    >;
    RefundERC20: TypedContractEvent<
      RefundERC20Event.InputTuple,
      RefundERC20Event.OutputTuple,
      RefundERC20Event.OutputObject
    >;

    "RefundETH(address,uint256)": TypedContractEvent<
      RefundETHEvent.InputTuple,
      RefundETHEvent.OutputTuple,
      RefundETHEvent.OutputObject
    >;
    RefundETH: TypedContractEvent<
      RefundETHEvent.InputTuple,
      RefundETHEvent.OutputTuple,
      RefundETHEvent.OutputObject
    >;

    "SetDefaultERC20Gateway(address,address)": TypedContractEvent<
      SetDefaultERC20GatewayEvent.InputTuple,
      SetDefaultERC20GatewayEvent.OutputTuple,
      SetDefaultERC20GatewayEvent.OutputObject
    >;
    SetDefaultERC20Gateway: TypedContractEvent<
      SetDefaultERC20GatewayEvent.InputTuple,
      SetDefaultERC20GatewayEvent.OutputTuple,
      SetDefaultERC20GatewayEvent.OutputObject
    >;

    "SetERC20Gateway(address,address,address)": TypedContractEvent<
      SetERC20GatewayEvent.InputTuple,
      SetERC20GatewayEvent.OutputTuple,
      SetERC20GatewayEvent.OutputObject
    >;
    SetERC20Gateway: TypedContractEvent<
      SetERC20GatewayEvent.InputTuple,
      SetERC20GatewayEvent.OutputTuple,
      SetERC20GatewayEvent.OutputObject
    >;

    "SetETHGateway(address,address)": TypedContractEvent<
      SetETHGatewayEvent.InputTuple,
      SetETHGatewayEvent.OutputTuple,
      SetETHGatewayEvent.OutputObject
    >;
    SetETHGateway: TypedContractEvent<
      SetETHGatewayEvent.InputTuple,
      SetETHGatewayEvent.OutputTuple,
      SetETHGatewayEvent.OutputObject
    >;
  };
}
